version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-authorizer-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5tgrg39tlnht"
s3_prefix = "lambda-authorizer-example"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
